Add GDB to amd64 test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -61,7 +61,34 @@ jobs:
         run: cmake --build --preset $PRESET --
 
       - name: CMake Test
+        if: matrix.preset.arch != 'amd64'
         run: cmake --build --preset $PRESET --target test
+
+      - name: CMake Test (with GDB)
+        if: matrix.preset.arch == 'amd64'
+        run: |
+          # Install GDB
+          sudo apt-get install -y gdb
+          echo "GDB installation complete"
+          
+          # Don't immediately fail if GDB exits with a non-zero code
+          set +e
+
+          # Capture GDB output (timeout 3 hours)
+          gdb_output=$(gdb -batch -ex run -ex "thread apply all bt" --args cmake --build --preset $PRESET --target test)
+          echo "$gdb_output"
+
+          # Summarize should fail the job if it fails
+          set -e
+
+          # Evaluate GDB exit code and exit this workflow accordingly
+          if echo "$gdb_output" | tail -n 100 | grep -q "exited normally"; then
+            exit 0
+          # Else, something failed, exit 1
+          else
+            exit 1
+          fi
+          
 
       - name: Upload Test Results
         if: always()
